name: build

permissions:
    contents: write
on:
  push:
    branches:
      - '**'
    tags: 
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build
    uses: ./.github/workflows/release.yml
    secrets: inherit
